import { ApiProperty } from '@nestjs/swagger';
import {
  CATEGORIES,
  type Category,
  type Priority,
  PRIORITIES,
} from '@/core/domain';
import { Report } from '@/reports/entities/report.entity';

export class ReportResponseDto {
  @ApiProperty({ example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' })
  id!: string;

  @ApiProperty({ example: 'Buraco na calçada' })
  title!: string;

  @ApiProperty({
    example: 'Tem um buraco enorme na calçada na frente do número 42.',
  })
  description!: string;

  @ApiProperty({
    example: 'Rua das Flores, 42, Centro, São Paulo - SP, 01310-100',
  })
  location!: string;

  @ApiProperty({ enum: CATEGORIES, example: 'Via Pública' })
  category!: Category;

  @ApiProperty({ enum: PRIORITIES, example: 'Alta' })
  priority!: Priority;

  @ApiProperty({
    description:
      'Formal technical summary generated by AI for public administrators',
    example:
      'Dano estrutural crítico identificado em calçada pública. Risco de queda para pedestres.',
  })
  technicalSummary!: string;

  @ApiProperty({ example: '2026-03-11T16:00:00.000Z' })
  createdAt!: Date;

  static fromEntity(report: Report): ReportResponseDto {
    return {
      id: report.id,
      title: report.title,
      description: report.description,
      location: report.location,
      category: report.category,
      priority: report.priority,
      technicalSummary: report.technicalSummary,
      createdAt: report.createdAt,
    };
  }
}
